{% set name = "yamldoc" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yamldoc-{{ version }}.tar.gz
  sha256: eb169566e8c1cf732b37b15537af05ce84df37372cdf496986501aa532b7d273

build:
  entry_points:
    - yamldoc = yamldoc:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - yamldoc
  commands:
    - pip check
    - yamldoc --help
  requires:
    - pip

about:
  home: https://github.com/Chris1221/yamldoc
  doc_url: https://chrisbcole.me/yamldoc/
  summary: Documentation engine for YAML.
  # PR made upstream to package in license
  license_file: LICENSE
  license: MIT

extra:
  recipe-maintainers:
    - thewchan
